openapi: 3.0.1
info:
  title: Ask Cetus
  description: This plugin is your go-to resource for key information on Cetus DEX, such as the number of pools and the price of each pool. Stay informed and make the best decisions with Cetus Assistant.
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /api/v1/cetus/pools_info:
    get:
      operationId: askCetus
      summary: Get the list of cetus pools
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getPoolsResponse"

components:
  schemas:
    getPoolsResponse:
      type: array
      items:
        type: object
        properties:
          symbol:
            type: string
            description: The symbol of pool.
          name:
            type: string
            description: The name of pool.
          fee:
            type: string
            description: The fee rate of pool.
          tick_spacing:
            type: string
            description: The tick spacing of pool, this is feature of uniswap v3.
          address:
            type: string
            description: The address of pool.
          coin_a_address:
            type: string
            description: The coin a address of pool.
          coin_b_address:
            type: string
            description: The coin b address of pool.
          is_closed:
            type: bool
            description: If pool closed.
          price:
            type: string
            description: The price of pool. One coin a can swap how much coin b.
